# Deploy Packages to test sevrer 
on: 
  push:
    branches: 
      - 'feature*'
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Get changed files
      uses: actions/checkout@v3
      with:
        repository: Sandeep084b/Demo
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
        
        
    - name: Copy folders from another Repo    
      run: |
        mkdir -p common-packages
        cp -r AH_Demo common-packages/
        cp -r AH_Demo_01 common-packages/
      working-directory: ${{ github.workspace }} 
     
           
    - name: Copy Folders from current Repo
      run: |
        mkdir -p business-packages
        cp -r AH_Sample business-packages/
        cp -r AH_Test business-packages/
      working-directory: ${{ github.workspace }} 
      
    - name: check contents from Common Folders
      run: |
        cd business-packages/
        ls-l
        cd ..
        cd common-packages/
        ls -l
