# Deploy Packages to test server 
on: 
  push:
    branches: 
      - 'feature*'
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v3
    
    - name: Checkout Current Folder
      uses: actions/checkout@v3
      with: 
        repository: Sandeep084b/Demo01
        ref: feature04
        path: Demo01
      
    - name: Copy folders from current Repo    
      run: |
        cd Demo01/
        mkdir -p Deso-packages
        while IFS= read -r package; do
            cp -r $package Deso-packages/
        done < package-list.txt
        #cp -r AH_Sample Deso-packages/
        #cp -r AH_Test Deso-packages/
        pwd
      working-directory: ${{ github.workspace }} 
     
    - name: Checkout Another Repo
      uses: actions/checkout@v3
      with: 
        repository: Sandeep084b/Demo
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
        path: Demo

    - name: Copy Folders from Other Repo
      run: |
        cd ..
        while IFS= read -r package; do
            cp -r Demo/$package Demo01/Deso-packages/
        done < Demo01/common-list.txt
        #cp -r Demo/AH_Demo Demo01/Deso-packages/
        #cp -r Demo/AH_Demo_01 Demo01/Deso-packages/
        pwd
      working-directory: ${{ github.workspace }} 
      
    - name: check contents from Common Folders
      run: |
        cd Demo01/Deso-packages/
        ls -l
        
    - name: Build Docker Image
      uses: docker/login-action@v3 
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: Demo01
        tags: sandy1101/msr_demo:latest
        
