# Deploy Packages to test sevrer 
on: 
  push:
    branches: 
      - 'feature*'
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v3
    
    - name: Checkout Current Folder
      uses: actions/checkout@v3
      with: 
        repository: Sandeep084b/Demo01
        ref: feature04
        path: Demo01
      
    - name: Copy folders from current Repo    
      run: |
        cd Demo01/
        mkdir -p Deso-packages
        cp -r AH_Sample Deso-packages/
        cp -r AH_Test Deso-packages/
        pwd
      working-directory: ${{ github.workspace }} 
     
    - name: Checkout Anther Repo
      uses: actions/checkout@v3
      with: 
        repository: Sandeep084b/Demo
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
        path: Demo

    - name: Copy Folders from current Repo
      run: |
        cp -r Demo/AH_Demo Demo01/Deso-packages/
        cp -r Demo/AH_Demo_01 Demo01/Deso-packages/
        pwd
      working-directory: ${{ github.workspace }} 
      
    - name: check contents from Common Folders
      run: |
        cd Deso-packages/
        ls -l
        
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}
      run: |
        pwd
        cd Demo01/
        ls -ltr
        docker build -t my-msr-image .
        
    - name: Push Docker image to Registery
      run: |
        docker tag my-msr-image msr_demo/my-msr-image
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }} msr_demo
        docker push msr_demo/my-msr-image
        
