# Deploy Packages to test sevrer 
on: 
  push:
    branches: 
      - 'feature*'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        separator: ","
      run: |
        mkir -p common-packages
        cp -r AH_Sample common-packages/
        cp -r AH_Test common-packages/
        cd common-packages/
        ls -l
      working-directory: ${{ github.workspace }} 
     
    - name: Check out my other private repo  
      uses: actions/checkout@v3
      with:
        repository: Sandeep084b/Demo
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
        
    - name: Copy Folders from another Repo
      run: | 
        mkdir -p common-packages
        cp -r AH_Demo common-packages/
        cp -r AH_Demo_01 common-packages/
        cd common-packages/
        ls -l
      working-directory: ${{ github.workspace }} 
