# Deploy Packages to test sevrer 
on: 
  push:
    branches: 
      - 'feature*'
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Get changed files
      uses: actions/checkout@v3
      with:
        repository: Sandeep084b/Demo01
        token: ${{ secrets.GIT_TOKEN }}
        ref: main
        
        
    - name: Copy folders from current Repo    
      run: |
        mkdir -p common-packages
        cp -r AH_Sample common-packages/
        cp -r AH_Test common-packages/
        cd common-packages/
        ls -l
      working-directory: ${{ github.workspace }} 
     
    - name: Check out my other private repo  
      uses: actions/checkout@v3
      with:
        repository: Sandeep084b/Demo
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
        
    - name: Copy Folders from another Repo
      run: | 
        #mkdir -p common-packages
        cp -r AH_Demo common-packages/
        cp -r AH_Demo_01 common-packages/
        cd common-packages/
        ls -l
      working-directory: ${{ github.workspace }} 
