# Deploy Packages to test sevrer 
on: 
  push:
    branches: 
      - 'feature*'
    
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: Get changed files
      uses: actions/checkout@v3
      with: 
        repository: Sandeep084b/Demo01
        ref: main
        path: Demo01
      
    - name: Copy folders from current Repo    
      run: |
        mkdir -p common-packages
        cp -r Demo01/AH_Sample common-packages/
        cp -r Demo01/AH_Test common-packages/
        pwd
      working-directory: ${{ github.workspace }} 
     
    - name: Checkout Anther Repo
      uses: actions/checkout@v3
      with: 
        repository: Sandeep084b/Demo
        token: ${{ secrets.GIT_TOKEN }}
        ref: master
        path: Demo

    - name: Copy Folders from current Repo
      run: |
        mkdir -p business-packages
        cp -r Demo/AH_Demo business-packages/
        cp -r Demo/AH_Demo_01 business-packages/
        pwd
      working-directory: ${{ github.workspace }} 
      
    - name: check contents from Common Folders
      run: |
        cd business-packages/
        ls -l
        cd ..
        cd common-packages/
        ls -l
